export const RECEIVE_SEARCH_RESULTS = 'RECEIVE_SEARCH_RESULTS';
export const SELECT_ARTICLE = 'SELECT_ARTICLE';
export const RECEIVE_ARTICLE_FROM_FIREBASE = 'RECEIVE_ARTICLE_FROM_FIREBASE';
export const REMOVE_ARTICLE = 'REMOVE_ARTICLE';