export const RECEIVE_SEARCH_RESULTS = 'RECEIVE_SEARCH_RESULTS';
export const SELECT_ARTICLE = 'SELECT_ARTICLE';
export const RECEIVE_ARTICLE_FROM_FIREBASE = 'RECEIVE_ARTICLE_FROM_FIREBASE';
export const REMOVE_ARTICLE = 'REMOVE_ARTICLE';
export const SEARCH_ERROR = 'SEARCH_ERROR';
export const CREATE_ARTICLE = 'CREATE_ARTICLE';
export const CREATE_ARTICLE_ERROR = 'CREATE_ARTICLE_ERROR';